---
- hosts: all
  tasks:
  - name: Add key for Docker repository
    apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9 state=present
  - name: Add Docker repository
    apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present
  - name: Install Docker
    apt: name=docker-engine update_cache=yes state=present
  - name: Install pip
    apt:
      pkg: "{{ item }}"
      state: installed
    with_items:
      - python-dev
      - python-pip
  - name: Install Docker-py
    pip:
      name: docker-py
  - name: Make sure docker is running
    service:
      name: docker
      state: started
