---
- hosts: all
  tasks:
  - name: Add key for Docker repository
    apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D state=present
  - name: Add Docker repository
    apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present
  - name: Install Docker
    apt: name=docker-engine update_cache=yes state=present
  - name: Install pip
    apt:
      pkg: "{{ item }}"
      state: installed
    with_items:
      - python-dev
      - python-pip
  - name: Install Docker-py
    pip:
      name: docker-py
  - name: Make sure docker is running
    service:
      name: docker
      state: started
