---
- hosts: all
  tasks:
  - name: Check WireGuard Status
    shell: wg
    register: wg_status
    
    

  - name: Re-enable WireGuard DKMS modules
    shell: "{{ item }}"
    with_items:
    - apt-get install  linux-headers-$(uname -r)
    - apt-get --reinstall install wireguard-dkms
    - wg-quick up wg0
    when: wg_status.stdout == ""
