---
- hosts: all
  tasks:
  - name: List Installed Updates
    win_shell: Get-HotFix
  - name: Scan for Available Updates
    win_updates:
      category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
      state: searched
  - name: Run Windows Update
    win_updates:
      category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
      reboot: yes
