---
- hosts: all
  tasks:
  - name: List Installed Updates
    win_shell: |
      $Session = New-Object -ComObject "Microsoft.Update.Session"
      $Searcher = $Session.CreateUpdateSearcher()
      $historyCount = $Searcher.GetTotalHistoryCount()
      $Searcher.QueryHistory(0, $historyCount) | Select-Object Date,
        @{name="Operation"; expression={switch($_.operation){
          1 {"Installation"}; 2 {"Uninstallation"}; 3 {"Other"}}}},
        @{name="Status"; expression={switch($_.resultcode){
          1 {"In Progress"}; 2 {"Succeeded"}; 3 {"Succeeded With Errors"};
          4 {"Failed"}; 5 {"Aborted"}
      }}}, Title 
  - name: Scan for Available Updates
    win_updates:
      category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
      state: searched
  - name: Run Windows Update
    win_updates:
      category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
      reboot: yes
