---
- hosts: all
  tasks:
  - name: List Installed Updates
    win_shell: |
      $Session = New-Object -ComObject "Microsoft.Update.Session"
      $Searcher = $Session.CreateUpdateSearcher()
      $historyCount = $Searcher.GetTotalHistoryCount()
      $Searcher.QueryHistory(0, $historyCount) | Select-Object Date,
        @{name="Operation"; expression={switch($_.operation){
          1 {"Installation"}; 2 {"Uninstallation"}; 3 {"Other"}}}},
        @{name="Status"; expression={switch($_.resultcode){
          1 {"In Progress"}; 2 {"Succeeded"}; 3 {"Succeeded With Errors"};
          4 {"Failed"}; 5 {"Aborted"}
      }}}, Title
  - name: List Available Categories
    win_updates:
      state: searched
  - name: Scan for All Available Updates
    win_updates:
      category_names: ['Application', 'Connectors', 'CriticalUpdates', 'DefinitionUpdates', 'DeveloperKits', 'FeaturePacks', 'Guidance', 'SecurityUpdates', 'ServicePacks', 'Tools', 'UpdateRollups', 'Updates']
      state: searched
  - name: Install Select Available Updates
    win_updates:
      category_names: ['Application', 'CriticalUpdates', 'DefinitionUpdates', 'FeaturePacks', 'SecurityUpdates', 'UpdateRollups', 'Updates']
      reboot: yes
